import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/druid"),
);
const icons = requireAll(require.context("../../assets/icons/druid"));

export const data: TalentData = {
  Balance: {
    name: "Balance",
    background: backgrounds["balance"],
    icon: icons["spell_nature_starfall"],
    talents: {
      "Improved Wrath": {
        name: "Improved Wrath",
        pos: "a1",
        icon: icons["spell_nature_abolishmagic"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Reduces the cast time of your Wrath spell by ${[
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
        ]} sec.`,
      },
      "Nature's Grasp": {
        name: "Nature's Grasp",
        pos: "a2",
        icon: icons["spell_nature_natureswrath"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`While active, any time an enemy strikes the caster they have a 35% chance to become afflicted by Entangling Roots (Rank 1). Only useable outdoors. 1 charge. Lasts 45 sec.`,
      },
      "Improved Nature's Grasp": {
        name: "Improved Nature's Grasp",
        pos: "a3",
        icon: icons["spell_nature_natureswrath"],
        maxRank: 4,
        reqPoints: 0,
        prereq: "Nature's Grasp",
        arrows: [{ dir: "right", from: "a2", to: "a3" }],
        description: talentText`Increases the chance of your Nature's Grasp to entangle an enemy by ${[
          15,
          30,
          45,
          65,
        ]}%.`,
      },
      "Improved Entangling Roots": {
        name: "Improved Entangling Roots",
        pos: "b1",
        icon: icons["spell_nature_stranglevines"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Gives you a ${[
          40,
          70,
          100,
        ]}% chance to avoid interruption caused by damage while casting Entangling Roots.`,
      },
      "Improved Moonfire": {
        name: "Improved Moonfire",
        pos: "b1",
        icon: icons["spell_nature_starfall"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases the damage and critical strike chance of your Moonfire spell by ${[
          10,
          20,
          30,
        ]}%.`,
      },
      "Natural Weapons": {
        name: "Natural Weapons",
        pos: "b2",
        icon: icons["inv_staff_01"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases the damage you deal with physical attacks in all forms by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Cycle of Life": {
        name: "Cycle of Life",
        pos: "b4",
        icon: icons["cycle_life"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Gives you a ${[
          50,
          100,
        ]}% chance to gain a 100% bonus to your Spirit after killing a target that yields experience.  For the duration, your Mana will regenerate at a 50% rate while casting.  Lasts 15 sec.`,
      },
      "Brambles": {
        name: "Brambles",
        pos: "c1",
        icon: icons["spell_nature_thorns"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases the damage caused by your Thorns and Entangling Root spells by ${[
          25,
          50,
          75,
        ]}%.`,
      },
      "Omen of Clarity": {
        name: "Omen of Clarity",
        pos: "c3",
        icon: icons["spell_nature_crystalball"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Natural Weapons",
        arrows: [
          { dir: "right-down", from: "b2", to: "b3" },
          { dir: "right-down-down", from: "b3", to: "c3" },
        ],
        description: talentText`Imbues the Druid with natural energy.  Each of the Druid's melee attacks has a chance to reduce the cost and to increase critical strike chance of your next damage or healing spell by 100%.  Lasts 2 min.`,
      },
      "Nature's Reach": {
        name: "Nature's Reach",
        pos: "c4",
        icon: icons["spell_nature_naturetouchgrow"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases the range of your Wrath, Entangling Roots, Faerie Fire, Moonfire, Starfire, and Hurricane spells by ${[
          10,
          20,
        ]}%.`,
      },
      Vengeance: {
        name: "Vengeance",
        pos: "d2",
        icon: icons["spell_nature_purge"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Natural Weapons",
        arrows: [{ dir: "down", from: "b2", to: "d2" }],
        description: talentText`Increases the critical strike damage bonus of your Starfire, Moonfire, and Wrath spells by ${[
          20,
          40,
          60,
          80,
          100,
        ]}%.`,
      },
      "Improved Starfire": {
        name: "Improved Starfire",
        pos: "c4",
        icon: icons["spell_arcane_starfire"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Reduces the cast time of Starfire by ${[
          0.2,
          0.4,
          0.6,
          0.8,
          1,
        ]} sec and has a ${[
          5,
          10,
          15,
          20,
          25,
        ]}% chance to stun the target for 3 sec.`,
      },
      "Improved Faerie Fire": {
        name: "Improved Faerie Fire",
        pos: "d1",
        icon: icons["spell_nature_faeriefire"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Increases the range and armor reduction of your Faerie Fire spells by ${[
          10,
          20,
          30,
          40,
          50,
        ]}%`,
      },
      "Power of Nature": {
        name: "Power of Nature",
        pos: "d3",
        icon: icons["power_of_nature"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Increases the duration of your Moonfire, Insect Swarm, Faerie Fire, Rejuvenation, Regrowth, Hibernate, Soothe Animal and Abolish Poison by ${[
          25,
          50,
        ]}%.`,
      },
      "Omnipraesentia Naturae": {
        name: "Omnipraesentia Naturae",
        pos: "e1",
        icon: icons["omni_natur"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases the range of your offensive Balance spells by ${[
          10,
          20,
        ]}% and reduces the chance for enemies to resist them by ${[
          2,
          4,
        ]}%.`,
      },

      "Nature's Grace": {
        name: "Nature's Grace",
        pos: "e2",
        icon: icons["spell_nature_naturesblessing"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`All spell criticals grace you with the blessing of nature, reducing the casting time of your next spell by 0.5 sec.`,
      },
      Moonglow: {
        name: "Moonglow",
        pos: "e3",
        icon: icons["spell_nature_sentinal"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Reduce the Mana cost of your Moonfire, Starfire, Wrath, Healing Touch, Regrowth and Rejuvenation spells by ${[
          7,
          14,
          21,
        ]}%.`,
      },
      Dreamstate: {
        name: "Dreamstate",
        pos: "e4",
        icon: icons["dreamstate"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Regenerates ${[
          1,
          2,
          3,
        ]}% of your total Mana every 5sec.`,
      },
      "Nature Balancer": {
        name: "Nature Balancer",
        pos: "f2",
        icon: icons["nature_balancer"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Nature's Grace",
        arrows: [{ dir: "down", from: "e2", to: "f2" }],
        description: talentText`Your Wrath spell have a ${[
          5,
          10,
          15,
          20,
          25,
        ]}% chance to increase critical strike chance of your next Moonfire or Starfire by 30% and your Moonfire or Starfire spells have a ${[
          5,
          10,
          15,
          20,
          25,
        ]}% chance to increase critical strike chance of your next Wrath by 30%.`,
      },

      Moonfury: {
        name: "Moonfury",
        pos: "f3",
        icon: icons["spell_nature_moonglow"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases the damage done by your Starfire, Moonfire and Wrath spells by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%`,
      },
      "Moonkin Form": {
        name: "Moonkin Form",
        pos: "g2",
        icon: icons["spell_nature_forceofnature"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`Transforms the Druid into Moonkin Form. While in this form the armor contribution from items is increased by 360% and all party members within 30 yards have their spell critical chance increased by 3%. The Moonkin can only cast Balance spells while shapeshifted.\n\nThe act of shapeshifting frees the caster of Polymorph and Movement Impairing effects.`,
      },
    },
  },
  "Feral Combat": {
    name: "Feral Combat",
    background: backgrounds["feral"],
    icon: icons["ability_racial_bearform"],
    talents: {
      Ferocity: {
        name: "Ferocity",
        pos: "a1",
        icon: icons["ability_hunter_pet_hyena"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Reduces the cost of your Maul, Swipe, Claw and Rake abilities by ${[
          1,
          2,
          3,
          4,
          5,
        ]} Rage or Energy.`,
      },
      "Feral Aggression": {
        name: "Feral Aggression",
        pos: "a2",
        icon: icons["ability_druid_demoralizingroar"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`Increases the effectiveness of your Demoralizing Roar by ${[
          20,
          40,
        ]}% and the damage caused by your Ferocious Bite by ${[
          10,
          20,
        ]}%.`,
      },
      "Feral Instinct": {
        name: "Feral Instinct",
        pos: "d1",
        icon: icons["ability_ambush"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Increases the threat caused in Bear and Dire Bear forms by ${[
          5,
          10,
          15,
        ]}%, reduces the chance enemies have to detect you while Prowling and increases the duration of your Tiger's Fury and Challenging Roar abilities by ${[
          3,
          6,
          9,
        ]} sec.`,
      },
      "Brutal Impact": {
        name: "Brutal Impact",
        pos: "b2",
        icon: icons["ability_druid_bash"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases the stun duration of your Bash and Pounce abilities by ${[
          1,
          2,
        ]} sec.`,
      },
      "Thick Hide": {
        name: "Thick Hide",
        pos: "a3",
        icon: icons["inv_misc_pelt_bear_03"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Increases your Armor contribution from items by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      "Primal Tenacity": {
        name: "Primal Tenacity",
        pos: "b1",
        icon: icons["primal_tenacity"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your chance to resist Stun and Fear effects by an additional ${[
          10,
          20,
          30,
        ]}% and reduces cooldown of your Enrage ability by ${[
          10,
          20,
          30,
        ]} sec.`,
      },

      "Feline Swiftness": {
        name: "Feline Swiftness",
        pos: "c1",
        icon: icons["spell_nature_spiritwolf"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your movement speed by ${[
          15,
          30,
        ]}% while outdoors in Cat Form and increases your chance to dodge while in Cat Form by ${[
          2,
          4,
        ]}%.`,
      },
      "Feral Charge": {
        name: "Feral Charge",
        pos: "c2",
        icon: icons["ability_hunter_pet_bear"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Causes you to charge an enemy, immobilizing and interrupting any spell being cast for 4 sec.`,
      },
      "Leap": {
        name: "Leap",
        pos: "c4",
        icon: icons["leap"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Leaps forward. Leap distance is highly dependent on the terrain. Also breaks movement impairing effects.`,
      },

      "Sharpened Claws": {
        name: "Sharpened Claws",
        pos: "b3",
        icon: icons["inv_misc_monsterclaw_04"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your critical strike chance while in Bear, Dire Bear or Cat Form by ${[
          2,
          4,
          6,
        ]}%.`,
      },
      "Stalker": {
        name: "Stalker",
        pos: "d2",
        icon: icons["spell_shadow_vampiricaura"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Increases the critical strike chance of your Ravage and Shred abilities by ${[
          15,
          30,
        ]}%.`,
      },
      "Predatory Strikes": {
        name: "Predatory Strikes",
        pos: "e2",
        icon: icons["ability_hunter_pet_cat"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases the critical strike damage bonus of your Feral Combat abilities by ${[
          10,
          20,
          30,
        ]}%. In addition, increases your attack power in Cat, Bear and Dire Bear Forms by ${[
          100,
          200,
          300,
        ]}% of your level.`,
      },
      "Blood Frenzy": {
        name: "Blood Frenzy",
        pos: "c3",
        icon: icons["ability_ghoulfrenzy"],
        maxRank: 2,
        reqPoints: 10,
        prereq: "Sharpened Claws",
        arrows: [{ dir: "down", from: "b3", to: "c3" }],
        description: talentText`Your critial strikes from Cat Form abilities that add combo points have a ${[
          50,
          100,
        ]}% chance to add an additional combo point.`,
      },
      "Primal Fury": {
        name: "Primal Fury",
        pos: "b4",
        icon: icons["ability_racial_cannibalize"],
        maxRank: 2,
        reqPoints: 5,
        prereq: "Sharpened Claws",
        arrows: [{ dir: "right", from: "b3", to: "b4" }],
        description: talentText`Gives you ${[
          50,
          100,
        ]} chance to gain an additional 5 Rage anytime you get a critical strike while in Bear and Dire Bear Form.`,
      },
      "Savage Fury": {
        name: "Savage Fury",
        pos: "e1",
        icon: icons["ability_druid_ravage"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases the damage caused by your Claw, Rake, Maul and Swipe abilities by ${[
          15,
          30,
        ]}%.`,
      },
      "Untamed Heart": {
        name: "Untamed Heart",
        pos: "e3",
        icon: icons["untamed_heart"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Heart of the Wild",
        arrows: [{ dir: "down", from: "d3", to: "e3" }],
        description: talentText`Heals yourself for 30% of your maximum health, and increases your maximum health by 30% for 20 sec.`,
      },
      "Heart of the Wild": {
        name: "Heart of the Wild",
        pos: "d3",
        icon: icons["spell_holy_blessingofagility"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Increases your Intellect and Spirit by ${[
          5,
          10,
          15,
          20,
          25,
        ]}%. In addition, while in Bear or Dire Bear Form your Stamina is increased by ${[
          5,
          10,
          15,
          20,
          25,
        ]}% and while in Cat Form your Strength is increased by ${[
          5,
          10,
          15,
          20,
          25,
        ]}%.`,
      },
      "Killer Instincts": {
        name: "Killer Instincts",
        pos: "f2",
        icon: icons["killer_instincts"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases all damage caused by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%. In addition, your melee critical strikes will increase your attack speed by ${[
          10,
          20,
          30,
          40,
          50,
        ]}% for your next 3 attacks.`,
      },
      "Survival Instincts": {
        name: "Killer Instincts",
        pos: "f3",
        icon: icons["survival_instincts"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Reduces the chance you'll be critically hit by melee attacks by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%. In addition, your melee critical strikes restore ${[
          1,
          2,
          3,
          4,
          5,
        ]}% Health to you.`,
      },

      "Leader of the Pack": {
        name: "Leader of the Pack",
        pos: "g2",
        icon: icons["spell_nature_unyeildingstamina"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`While in Cat, Bear or Dire Bear Form, the Leader of the Pack increases ranged and melee critical chance of all party members within 20 yards by 3%`,
      },
    },
  },
  Restoration: {
    name: "Restoration",
    background: backgrounds["restoration"],
    icon: icons["spell_nature_healingtouch"],
    talents: {
      Accuracy: {
        name: "Accuracy",
        pos: "a1",
        icon: icons["accuracy"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Increases your chance to hit with all attacks and spells by ${[
          1,
          2,
          3,
        ]}%.`,
      },
      "Natural Shapeshifter": {
        name: "Natural Shapeshifter",
        pos: "a4",
        icon: icons["natural_shapeshifter"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Reduces the mana cost of all shapeshifting by ${[
          20,
          40,
          60,
        ]}%.`,
      },
      "Improved Mark of the Wild": {
        name: "Improved Mark of the Wild",
        pos: "c4",
        icon: icons["spell_nature_regeneration"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases the effects of your Mark of the Wild and Gift of the Wild spells by ${[
          10,
          20,
          30,
          40,
          50,
        ]}% and reduces the chance of listed spells to be dispelled by ${[
          15,
          30,
          45,
          60,
          75,
        ]}%.`,
      },
      Furor: {
        name: "Furor",
        pos: "a3",
        icon: icons["spell_nature_unyeildingstamina"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`Gives you ${[
          50,
          100,
        ]}% chance to gain 10 Rage when you shapeshift into Bear and Dire Bear Form or 40 Energy when you shapeshift into Cat Form.`,
      },
      "Naturalist": {
        name: "Naturalist",
        pos: "b1",
        icon: icons["spell_nature_healingtouch"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Reduces the cast time of your Healing Touch spell by ${[
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
        ]} sec and increases your Mana regeneration by ${[
          30,
          60,
          90,
          120,
          150,
        ]}% while in Cat, Bear or Dire Bear Form.`,
      },
      "Nature's Focus": {
        name: "Nature's Focus",
        pos: "a2",
        icon: icons["spell_nature_healingwavegreater"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Gives you a ${[
          15,
          30,
          45,
          60,
          75,
        ]}% chance to avoid interruption caused by damage while casting.`,
      },
      "Improved Enrage": {
        name: "Improved Enrage",
        pos: "b3",
        icon: icons["ability_druid_enrage"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`The Enrage ability now instantly generates ${[
          5,
          10,
        ]} Rage.`,
      },
      Reflection: {
        name: "Reflection",
        pos: "c3",
        icon: icons["spell_frost_windwalkon"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Allows ${[
          10,
          20,
          30,
        ]}% of your Mana regeneration to continue while casting.`,
      },
      "Insect Swarm": {
        name: "Insect Swarm",
        pos: "c2",
        icon: icons["spell_nature_insectswarm"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`The enemy is swarmed by insects causing 132 Nature damage over 24 sec.`,
      },
      Subtlety: {
        name: "Subtlety",
        pos: "b2",
        icon: icons["ability_eyeoftheowl"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Reduces the threat generated by your Healing spells by ${[
          5,
          10,
          15,
          20,
          25,
        ]}% and increases your chance to avoid area of effect spells by an additional ${[
          5,
          10,
          15,
          20,
          25,
        ]}%.`,
      },
      "Tranquil Spirit": {
        name: "Tranquil Spirit",
        pos: "e2",
        icon: icons["spell_holy_elunesgrace"],
        maxRank: 5,
        reqPoints: 20,
        description: talentText`Reduces the mana cost of your Healing Touch and Tranquility spells by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%. In addition, reduces threat caused by Tranquility by ${[
          20,
          40,
          60,
          80,
          100,
        ]}%.`,
      },
      "Improved Rejuvenation": {
        name: "Improved Rejuvenation",
        pos: "d3",
        icon: icons["spell_nature_rejuvenation"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Increases the effect of your Rejuvenation spell by ${[
          10,
          20,
          30,
        ]}%.`,
      },
      "The Caretaker": {
        name: "The Caretaker",
        pos: "d4",
        icon: icons["caretaker"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Reduces the Mana cost of your Soothe Animal, Hibernate, Remove Curse, Cure Poison, Abolish Poison and Rebirth spells by ${[
          10,
          20,
          30,
        ]}%.`,
      },
      "Custody of the Nature": {
        name: "Custody of the Nature",
        pos: "e4",
        icon: icons["custody_of_nature"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`After being struck by a critical hit, you become immune to critical strikes for next ${[
          3,
          6,
          9,
        ]} sec. In addition, gives your spell effects additional ${[
          20,
          40,
          60,
        ]}% chance to resist dispel effects..`,
      },

      "Nature's Swiftness": {
        name: "Nature's Swiftness",
        pos: "e1",
        icon: icons["spell_nature_ravenform"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Naturalist",
        arrows: [{ dir: "down", from: "b1", to: "e1" }],
        description: talentText`When activated, your next Nature spell becomes an instant cast spell.`,
      },
      "Gift of Nature": {
        name: "Gift of Nature",
        pos: "d3",
        icon: icons["spell_nature_protectionformnature"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Insect Swarm",
        arrows: [{ dir: "down", from: "c3", to: "d3" }],
        description: talentText`Increases nature damage by ${[
          2,
          4,
          6,
          8,
          10,
        ]}% and increases the effect of all healing spells by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Improved Tranquility": {
        name: "Improved Tranquility",
        pos: "e4",
        icon: icons["spell_nature_tranquility"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Reduces the threat caused by Tranquility by ${[
          50,
          100,
        ]}%.`,
      },
      "Animism": {
        name: "Animism",
        pos: "f1",
        icon: icons["animism"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases spell damage and healing by up to ${[
          5,
          10,
          15,
          20,
          25,
        ]}% of your total Spirit.`,
      },

      "Improved Regrowth": {
        name: "Improved Regrowth",
        pos: "f3",
        icon: icons["spell_nature_resistnature"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Gift of Nature",
        arrows: [{ dir: "down", from: "d3", to: "f3" }],
        description: talentText`Increases the critical effect chance of your Regrowth spell by ${[
          15,
          30,
          45,
          60,
          75,
        ]}%.`,
      },
      Swiftmend: {
        name: "Swiftmend",
        pos: "g2",
        icon: icons["inv_relics_idolofrejuvenation"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Tranquil Spirit",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`Consumes a Rejuvenation or Regrowth effect on a friendly target to instantly heal them an amount equal to 12 sec. of Rejuvenation or 18 sec. of Regrowth.`,
      },
    },
  },
};
