import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/hunter"),
);
const icons = requireAll(require.context("../../assets/icons/hunter"));

export const data: TalentData = {
  "Beast Mastery": {
    name: "Beast Mastery",
    background: backgrounds["beast-mastery"],
    icon: icons["ability_hunter_beasttaming"],
    talents: {
      "Improved Aspect of the Hawk": {
        name: "Improved Aspect of the Hawk",
        pos: "a2",
        icon: icons["spell_nature_ravenform"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`While Aspect of the Hawk is active, gives you a ${[
          20,
          40,
          60,
          80,
          100,
        ]}% chance of increasing ranged attack speed by 30% for 8 sec after dealing a critical strike with a ranged attack.`,
      },
      "Endurance Training": {
        name: "Endurance Training",
        pos: "a3",
        icon: icons["spell_nature_reincarnation"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases the Health of your pets by ${[
          5,
          10,
          15,
          20,
          25,
        ]}%.`,
      },
      "Improved Eyes of the Beast": {
        name: "Improved Eyes of the Beast",
        pos: "b1",
        icon: icons["ability_eyeoftheowl"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases the duration of your Eyes of the Beast by ${[
          30,
          60,
        ]} sec.`,
      },
      "Improved Aspect of the Monkey": {
        name: "Improved Aspect of the Monkey",
        pos: "a1",
        icon: icons["ability_hunter_aspectofthemonkey"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases the Dodge and melee crit bonus of your Aspect of the Monkey by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Thick Hide": {
        name: "Thick Hide",
        pos: "b3",
        icon: icons["inv_misc_pelt_bear_03"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases the Armor rating of your pets by ${[
          15,
          30,
          45,
        ]}%.`,
      },
      "Improved Revive Pet": {
        name: "Improved Revive Pet",
        pos: "b4",
        icon: icons["ability_hunter_beastsoothe"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Revive Pet's casting time is reduced by ${[
          3,
          6,
        ]} sec, mana cost is reduced by ${[
          25,
          50,
        ]}%, and increases the health your pet returns with by an additional ${[
          15,
          30,
        ]}%.`,
      },
      "Bestial Swiftness": {
        name: "Bestial Swiftness",
        pos: "b1",
        icon: icons["ability_druid_dash"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases the outdoor movement speed of your pets by ${[
          10,
          20,
          30,
        ]}%.`,
      },
      "Aspect Mastery": {
        name: "Aspect Mastery",
        pos: "c1",
        icon: icons["aspect_mastery"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases the effectiveness of your Aspect of the Cheetah, Aspect of the Pack and Aspect of the Wild by ${[
          25,
          50,
        ]}% and reduces mana cost of all your Aspects by 50%.`,
      },
      "Unleashed Fury": {
        name: "Unleashed Fury",
        pos: "c3",
        icon: icons["ability_bullrush"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases the damage done by your pets by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Survival Instincts": {
        name: "Survival Instincts",
        pos: "d1",
        icon: icons["survival_instincts"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Reduces the chance your pets are critically hit by melee attacks by ${[
          2,
          4,
          6,
        ]}% and increases the chance your pets avoid area of effect spells by an additional ${[
          15,
          30,
          45,
        ]}%.`,
      },
      "Improved Mend Pet": {
        name: "Improved Mend Pet",
        pos: "b2",
        icon: icons["ability_hunter_mendpet"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Gives the Mend Pet spell a ${[
          15,
          50,
        ]}% chance of cleansing 1 Curse, Disease, Magic or Poison effect from the pet each tick.`,
      },
      Ferocity: {
        name: "Ferocity",
        pos: "d3",
        icon: icons["inv_misc_monsterclaw_04"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Increases the critical strike chance of your pets by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Bestial Agility": {
        name: "Bestial Agility",
        pos: "d4",
        icon: icons["bestial_agility"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Increases your and your pets attack speed by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Spirit Bond": {
        name: "Spirit Bond",
        pos: "e1",
        icon: icons["ability_druid_demoralizingroar"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`While your pet is active, you and your pet will regenerate ${[
          3,
          6,
        ]}% of total health every 10 sec.`,
      },
      Intimidation: {
        name: "Intimidation",
        pos: "c2",
        icon: icons["ability_devour"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Command your pet to intimidate the target on the next successful melee attack, causing a high amount of threat and stunning the target for 3 sec.`,
      },
      "Bestial Discipline": {
        name: "Bestial Discipline",
        pos: "e4",
        icon: icons["spell_nature_abolishmagic"],
        maxRank: 5,
        reqPoints: 20,
        description: talentText`Increase the Focus regeneration of your pets by ${[
          20,
          40,
          60,
          80,
          100,
        ]}%.`,
      },
      Frenzy: {
        name: "Frenzy",
        pos: "f3",
        icon: icons["inv_misc_monsterclaw_03"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Ferocity",
        arrows: [{ dir: "down", from: "d3", to: "f3" }],
        description: talentText`Gives your pet a ${[
          20,
          40,
          60,
          80,
          100,
        ]}% chance to gain a 30% attack speed increase for 8 sec after dealing a critical strike.`,
      },
      "Bestial Wrath": {
        name: "Bestial Wrath",
        pos: "e2",
        icon: icons["ability_druid_ferociousbite"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Intimidation",
        arrows: [{ dir: "down", from: "c2", to: "e2" }],
        description: talentText`Send your pet into a rage causing 50% additional damage for 18 sec. While enraged, the beast does not feel pity or remorse or fear and it cannot be stopped unless killed.`,
      },
      "Team Play": {
        name: "Team Play",
        pos: "f1",
        icon: icons["team_play"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Spirit Bond",
        arrows: [{ dir: "down", from: "e1", to: "f1" }],
        description: talentText`Your attacks have a ${[
          3,
          6,
          9,
          12,
          15,
        ]}% chance to invigorate your pet. Invigorated pet instantly generates 50 Focus and frees from 1 Curse, Disease, Magic, Poison or Fear effects.

        Your pet attacks have a ${[
          3,
          6,
          9,
          12,
          15,
        ]}% chance to inspire you, reducing Mana cost of all your spells and abilities by 100% for 5 sec.`,
      },
      "Two Hearts One Soul": {
        name: "Two Hearts One Soul",
        pos: "g1",
        icon: icons["ability_druid_ferociousbite"],
        maxRank: 3,
        reqPoints: 30,
        prereq: "Intimidation",
        arrows: [{ dir: "down", from: "f1", to: "g1" }],
        description: talentText`Your pet gets Strength, Agility and Stamina equal to ${[
          15,
          30,
          50,
        ]}% of your Strength, Agility and Stamina.`,
      },
      "Kill Command": {
        name: "Kill Command",
        pos: "g2",
        icon: icons["kill_command"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Intimidation",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`Give the command to kill, increasing damage done by your pet by 100% for 5 sec. Only usable against enemies that have 20% or less health.`,
      },
    },
  },
  Marksmanship: {
    name: "Marksmanship",
    background: backgrounds["marksmanship"],
    icon: icons["ability_marksmanship"],
    talents: {
      "Improved Concussive Shot": {
        name: "Improved Concussive Shot",
        pos: "a2",
        icon: icons["spell_frost_stun"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Gives your Concussive Shot a ${[
          10,
          20,
          30,
        ]}% chance to stun the target for 3 sec.`,
      },
      Efficiency: {
        name: "Efficiency",
        pos: "a3",
        icon: icons["spell_frost_wizardmark"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Reduces the Mana cost of your Shots and Stings by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Improved Hunter's Mark": {
        name: "Improved Hunter's Mark",
        pos: "a1",
        icon: icons["ability_hunter_snipershot"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`Increases the Attack Power bonus of your Hunter's Mark spell by ${[
          20,
          40,
        ]}%. Reduce it's Mana cost by ${[
          50,
          100,
        ]}% and increases its duration by 1 min.`,
      },
      "Stalking": {
        name: "Stalking",
        pos: "b1",
        icon: icons["stalking"],
        maxRank: 2,
        reqPoints: 5,
        prereq: "Improved Hunter's Mark",
        arrows: [{ dir: "down", from: "a1", to: "b1" }],
        description: talentText`After killing an opponent that yields experience or honor, your next melee or ranged attack will increase your critical strike chance by ${[
          10,
          20,
        ]}% for 10 sec and your pet will generate 100 Focus. Also this attack generate no threat.

        In addition, reduces the cooldown of your Rapid Fire and Rapid Strikes abilities by ${[
          1,
          2,
        ]} minutes.`,
      },
      "Lethal Shots": {
        name: "Lethal Shots",
        pos: "b3",
        icon: icons["ability_searingarrow"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases your critical strike chance with ranged weapons by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%`,
      },
      "Aimed Shot": {
        name: "Aimed Shot",
        pos: "c1",
        icon: icons["inv_spear_07"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`An aimed shot that increases ranged damage by 70`,
      },
      "Snapshot": {
        name: "Snapshot",
        pos: "e1",
        icon: icons["Snapshot"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Lethal Shots",
        arrows: [{ dir: "down", from: "c1", to: "e1" }],
        description: talentText`Reduces the shot time of your Aimed Shot by ${[
          0.2,
          0.4,
          0.6,
          0.8,
          1,
        ]} sec and Multi Shot by ${[
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
        ]} sec.`,
      },
      "Improved Arcane Shot": {
        name: "Improved Arcane Shot",
        pos: "b2",
        icon: icons["ability_impalingbolt"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases the critical strike chance of your Arcane Shot by ${[
          15,
          30,
          45,
        ]}%.`,
      },
      "Hawk Eye": {
        name: "Hawk Eye",
        pos: "c4",
        icon: icons["ability_townwatch"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases the range of your ranged weapons by ${[
          2,
          4,
          6,
        ]} yards.`,
      },
      "Improved Stings": {
        name: "Improved Stings",
        pos: "c2",
        icon: icons["ability_hunter_quickshot"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases the damage done by your Serpent Sting and Wyvern Sting by ${[
          10,
          20,
          30,
        ]}% and the mana drained by your Viper Sting by ${[
          10,
          20,
          30,
        ]}%. 
        In addition, reduces the Stamina and Intellect of targets affected by your Scorpid Sting by 10% of the amount of Strength reduced.`,
      },
      "Mortal Shots": {
        name: "Mortal Shots",
        pos: "c3",
        icon: icons["ability_piercedamage"],
        maxRank: 5,
        reqPoints: 10,
        prereq: "Lethal Shots",
        arrows: [{ dir: "down", from: "b3", to: "c3" }],
        description: talentText`Increases your ranged weapon critical strike damage bonus by ${[
          6,
          12,
          18,
          24,
          30,
        ]}%.`,
      },
      "Scatter Shot": {
        name: "Scatter Shot",
        pos: "e3",
        icon: icons["ability_golemstormbolt"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`A short range shot that deals 50% wepon damage and disorients the target for 4 sec. Any damage caused will remove the effect. Turns off your attack when used.`,
      },
      "Bullseye": {
        name: "Bullseye",
        pos: "e4",
        icon: icons["Bullseye"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`When activated, increases the critical strike chance of your next Aimed Shot, Multi-Shot or Arcane Shot by 100%.`,
      },
      "Reconnaissance": {
        name: "Reconnaissance",
        pos: "f1",
        icon: icons["Reconnaissance"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases your damage by ${[
          5,
          10,
          15,
          20,
          25,
        ]}% if you are standing still. Usually reconnaissance takes 10 sec. It is allowed to move at a short distance without losing the effect.`,
      },

      Barrage: {
        name: "Barrage",
        pos: "e2",
        icon: icons["ability_upgrademoonglaive"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases the damage done by your Multi-Shot and Volley spells by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      "Improved Scorpid Sting": {
        name: "Improved Scorpid Sting",
        pos: "e3",
        icon: icons["ability_hunter_criticalshot"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Reduces the Stamina of targets affected by your Scorpid Sting by ${[
          10,
          20,
          30,
        ]}% of the amount of Strength reduced.`,
      },
      "Crossbow Specialization": {
        name: "Crossbow Specialization",
        pos: "d2",
        icon: icons["crossbow"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Increases your chance to get a critical strike with Crossbows by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Bow Specialization": {
        name: "Bow Specialization",
        pos: "d2",
        icon: icons["bow"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Gives you a ${[
          1,
          2,
          3,
          4,
          5,
        ]}% to launch an extra arrow to the same target after dealing damage with a bow.`,
      },
      "Gun Specialization": {
        name: "Gun Specialization",
        pos: "d3",
        icon: icons["gun"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Gives you a ${[
          2,
          4,
          6,
          8,
          10,
        ]}% to stun the target for 3 sec when dealing damage with your Gun.`,
      },
      "Ranged Weapon Specialization": {
        name: "Ranged Weapon Specialization",
        pos: "f3",
        icon: icons["inv_weapon_rifle_06"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases the damage your deal with ranged weapons by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Trueshot Aura": {
        name: "Trueshot Aura",
        pos: "g2",
        icon: icons["ability_trueshot"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Barrage",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`Increase the ranged attack power of party members within 45 yards by 100 and melee attack power by 50. Lasts 30 min.`,
      },
    },
  },
  Survival: {
    name: "Survival",
    background: backgrounds["survival"],
    icon: icons["ability_hunter_swiftstrike"],
    talents: {
      "Monster Slaying": {
        name: "Monster Slaying",
        pos: "a1",
        icon: icons["inv_misc_head_dragon_black"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Increases all damage against Beasts, Giants and Dragonkin targets by ${[
          1,
          2,
          3,
        ]}% and increases critical damage caused against Beasts, Giants and Dragonkin targets by an additional ${[
          1,
          2,
          3,
        ]}%.`,
      },
      "Humanoid Slaying": {
        name: "Humanoid Slaying",
        pos: "a2",
        icon: icons["spell_holy_prayerofhealing"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Increases all damage against Humanoid targets by ${[
          1,
          2,
          3,
        ]}% and increases the critical damage caused against Humanoid targets by an additional ${[
          1,
          2,
          3,
        ]}%.`,
      },
      Deflection: {
        name: "Deflection",
        pos: "a3",
        icon: icons["ability_parry"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases your Parry chance by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      Entrapment: {
        name: "Entrapment",
        pos: "b1",
        icon: icons["spell_nature_stranglevines"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Gives your Immolation Trap, Frost Trap, and Explosive Trap a ${[
          5,
          10,
          15,
          20,
          25,
        ]}% chance to entrap the target, preventing them from moving for 5 sec.`,
      },
      "Savage Strikes": {
        name: "Savage Strikes",
        pos: "b2",
        icon: icons["ability_racial_bloodrage"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases the critical strike chance of Raptor Strike and Mongoose Bite by ${[
          10,
          20,
        ]}%.`,
      },
      "Improved Wing Clip": {
        name: "Improved Wing Clip",
        pos: "b3",
        icon: icons["ability_rogue_trip"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Gives your Wing Clip ability a ${[
          4,
          8,
          12,
          16,
          20,
        ]}% chance to immobilize the target for 5 sec.`,
      },
      "Clever Traps": {
        name: "Clever Traps",
        pos: "c1",
        icon: icons["spell_nature_timestop"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases the duration of Freezing and Frost trap effects by ${[
          15,
          30,
        ]}% and the damage of Immolation and Explosive trap by ${[15, 30]}%.`,
      },
      Survivalist: {
        name: "Survivalist",
        pos: "c2",
        icon: icons["spell_shadow_twilight"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases total health by ${[2, 4, 6, 8, 10]}%`,
      },
      Deterrence: {
        name: "Deterrence",
        pos: "c3",
        icon: icons["ability_whirlwind"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`When activated, increases your Dodge and Parry chance by 25% for 10 sec.`,
      },
      "Trap Mastery": {
        name: "Trap Mastery",
        pos: "d1",
        icon: icons["ability_ensnare"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Decreases the chance enemies will resist trap effects by ${[
          5,
          10,
        ]}%.`,
      },
      Surefooted: {
        name: "Surefooted",
        pos: "d2",
        icon: icons["ability_kick"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Increases hit chance by ${[
          1,
          2,
          3,
        ]}% and increases the chance movement impairing effects will be resisted by an additional ${[
          5,
          10,
          15,
        ]}%`,
      },
      "Improved Feign Death": {
        name: "Improved Feign Death",
        pos: "d4",
        icon: icons["ability_rogue_feigndeath"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Reduces the chance your Feign Death ability will be resisted by ${[
          2,
          4,
        ]}%.`,
      },
      "Killer Instinct": {
        name: "Killer Instinct",
        pos: "e2",
        icon: icons["spell_holy_blessingofstamina"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your critical strike chance with all attacks by ${[
          1,
          2,
          3,
        ]}%`,
      },
      Counterattack: {
        name: "Counterattack",
        pos: "e3",
        icon: icons["ability_warrior_challange"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Deterrence",
        arrows: [{ dir: "down", from: "c3", to: "e3" }],
        description: talentText`A strike that becomes active after parrying an opponent's attack. This attack deals 40 damage and immobilizes the target for 5 sec. Counterattack cannot be blocked, dodged, or parried.`,
      },
      "Lightening Reflexes": {
        name: "Lightening Reflexes",
        pos: "f3",
        icon: icons["spell_nature_invisibilty"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases your Agility by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%`,
      },
      "Wyvern Sting": {
        name: "Wyvern Sting",
        pos: "g2",
        icon: icons["inv_spear_02"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Killer Instinct",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`A stinging shot that puts the target to sleep for 12 sec. Any damage will cancel the effect. When the target wakes up, the Sting causes 0 Nature damage over 12 sec. Only usable out of combat. Only one Sting per Hunter can be active on the target at a time.`,
      },
    },
  },
};
