import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/hunter"),
);
const icons = requireAll(require.context("../../assets/icons/hunter"));

export const data: TalentData = {
  "Beast Mastery": {
    name: "Beast Mastery",
    background: backgrounds["beast-mastery"],
    icon: icons["ability_hunter_beasttaming"],
    talents: {
      "Improved Aspect of the Hawk": {
        name: "Improved Aspect of the Hawk",
        pos: "a2",
        icon: icons["spell_nature_ravenform"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`While Aspect of the Hawk is active, gives you a ${[
          20,
          40,
          60,
          80,
          100,
        ]}% chance of increasing ranged attack speed by 30% for 8 sec after dealing a critical strike with a ranged attack.`,
      },
      "Endurance Training": {
        name: "Endurance Training",
        pos: "a3",
        icon: icons["spell_nature_reincarnation"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`Increases the Health of your pets by ${[
          10,
          20,
        ]}%.`,
      },
      "Improved Aspect of the Monkey": {
        name: "Improved Aspect of the Monkey",
        pos: "a1",
        icon: icons["ability_hunter_aspectofthemonkey"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases the Dodge and melee crit bonus of your Aspect of the Monkey by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Thick Hide": {
        name: "Thick Hide",
        pos: "b1",
        icon: icons["inv_misc_pelt_bear_03"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases the Armor rating of your pets by ${[
          15,
          30,
          45,
        ]}%.`,
      },
      "Improved Revive Pet": {
        name: "Improved Revive Pet",
        pos: "b4",
        icon: icons["ability_hunter_beastsoothe"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Revive Pet's casting time is reduced by ${[
          3,
          6,
        ]} sec, mana cost is reduced by ${[
          50,
          100,
        ]}%, and increases the health your pet returns with by an additional ${[
          15,
          30,
        ]}%.`,
      },
      "Bestial Swiftness": {
        name: "Bestial Swiftness",
        pos: "c4",
        icon: icons["ability_druid_dash"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases the outdoor movement speed of your pets by ${[
          10,
          20,
          30,
        ]}% and their dodge chance by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      "Aspect Mastery": {
        name: "Aspect Mastery",
        pos: "b3",
        icon: icons["aspect_mastery"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases the effectiveness of your Aspect of the Cheetah, Aspect of the Pack and Aspect of the Wild by ${[
          25,
          50,
        ]}% and reduces mana cost of all your Aspects by 50%.`,
      },
      "Unleashed Fury": {
        name: "Unleashed Fury",
        pos: "c3",
        icon: icons["ability_bullrush"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases the damage done by your pets by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Survival Instincts": {
        name: "Survival Instincts",
        pos: "d1",
        icon: icons["survival_instincts"],
        maxRank: 3,
        reqPoints: 15,
        prereq: "Thick Hide",
        arrows: [{ dir: "down", from: "b1", to: "d1" }],
        description: talentText`Reduces the chance your pets are critically hit by melee attacks by ${[
          2,
          4,
          6,
        ]}% and increases the chance your pets avoid area of effect spells by an additional ${[
          15,
          30,
          45,
        ]}%.`,
      },
      "Improved Mend Pet": {
        name: "Improved Mend Pet",
        pos: "b2",
        icon: icons["ability_hunter_mendpet"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Gives the Mend Pet spell a ${[
          15,
          50,
        ]}% chance of cleansing 1 Curse, Disease, Magic or Poison effect from the pet each tick.`,
      },
      Ferocity: {
        name: "Ferocity",
        pos: "d3",
        icon: icons["inv_misc_monsterclaw_04"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Increases the critical strike chance of your pets by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Savage Flurry": {
        name: "Savage Flurry",
        pos: "e4",
        icon: icons["savage_flurry"],
        maxRank: 5,
        reqPoints: 20,
        description: talentText`Increases your and your pets attack speed by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Spirit Bond": {
        name: "Spirit Bond",
        pos: "f1",
        icon: icons["ability_druid_demoralizingroar"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Team Play",
        arrows: [{ dir: "down", from: "e1", to: "f1" }],
        description: talentText`Your pet gets Strength, Agility and Stamina equal to ${[
          10,
          20,
          30,
          40,
          50
        ]}% of your Strength, Agility and Stamina.\n\n While your pet is active you will regenerate ${[
          1,
          2,
          3,
          4,
          5
        ]}% of your total health every 5 sec.`,
      },
      Intimidation: {
        name: "Intimidation",
        pos: "c2",
        icon: icons["ability_devour"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Command your pet to intimidate the target on the next successful melee attack, causing a high amount of threat and stunning the target for 3 sec.`,
      },
      "Bestial Discipline": {
        name: "Bestial Discipline",
        pos: "d2",
        icon: icons["spell_nature_abolishmagic"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Increase the Focus regeneration of your pets by ${[
          50,
          100,
        ]}%.`,
      },
      Frenzy: {
        name: "Frenzy",
        pos: "f3",
        icon: icons["inv_misc_monsterclaw_03"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Ferocity",
        arrows: [{ dir: "down", from: "d3", to: "f3" }],
        description: talentText`Gives your pet a ${[
          20,
          40,
          60,
          80,
          100,
        ]}% chance to gain a 30% attack speed increase for 8 sec after dealing a critical strike.`,
      },
      "Bestial Wrath": {
        name: "Bestial Wrath",
        pos: "e2",
        icon: icons["ability_druid_ferociousbite"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Send your pet into a rage causing 50% additional damage for 18 sec. While enraged, the beast does not feel pity or remorse or fear and it cannot be stopped unless killed.`,
      },
      "Team Play": {
        name: "Team Play",
        pos: "e1",
        icon: icons["team_play"],
        maxRank: 5,
        reqPoints: 20,
        description: talentText`Your attacks have a ${[
          3,
          6,
          9,
          12,
          15,
        ]}% chance to invigorate your pet. Invigorated pet instantly generates 50 Focus and frees from 1 Curse, Disease, Magic, Poison or Fear effects.

        Your pet attacks have a ${[
          5,
          10,
          15,
          20,
          25,
        ]}% chance to inspire you, reducing Mana cost of all your spells and abilities by 100% for 5 sec.`,
      },
      "Terrifying Roar": {
        name: "Terrifying Roar",
        pos: "g3",
        icon: icons["terrifying_roar"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`Roars at an enemy, paralyzing it with terror for 5 sec and greatly reducing your threat for that target. In addition, up to 5 total enemies will flee in fear for 10 sec.`,
      },
      "Kill Command": {
        name: "Kill Command",
        pos: "g2",
        icon: icons["kill_command"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Bestial Wrath",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`Give the command to kill, increasing damage done by your pet by 50% for 5 sec. Only usable against enemies that have 20% or less health.`,
      },
    },
  },
  Marksmanship: {
    name: "Marksmanship",
    background: backgrounds["marksmanship"],
    icon: icons["ability_marksmanship"],
    talents: {
      "Improved Concussive Shot": {
        name: "Improved Concussive Shot",
        pos: "b2",
        icon: icons["spell_frost_stun"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Gives your Concussive Shot a ${[
          10,
          20,
          30,
        ]}% chance to stun the target for 3 sec.`,
      },
      Efficiency: {
        name: "Efficiency",
        pos: "a3",
        icon: icons["spell_frost_wizardmark"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Reduces the Mana cost of your Shots and Stings by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Improved Hunter's Mark": {
        name: "Improved Hunter's Mark",
        pos: "a1",
        icon: icons["ability_hunter_snipershot"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`Increases the Attack Power bonus of your Hunter's Mark spell by ${[
          20,
          40,
        ]}%. Reduce it's Mana cost by ${[
          50,
          100,
        ]}% and increases its duration by 1 min.`,
      },
      "Stalking": {
        name: "Stalking",
        pos: "b1",
        icon: icons["stalking"],
        maxRank: 2,
        reqPoints: 5,
        prereq: "Improved Hunter's Mark",
        arrows: [{ dir: "down", from: "a1", to: "b1" }],
        description: talentText`After killing an opponent that yields experience or honor, your critical strike chance is increased by ${[
          5,
          10,
        ]}% for 10 sec and threat generated by 90% for 20 sec.

        In addition, reduces the cooldown of your Rapid Fire and Rapid Strikes abilities by ${[
          1,
          2,
        ]} minutes.`,
      },
      "Lethal Shots": {
        name: "Lethal Shots",
        pos: "b3",
        icon: icons["ability_searingarrow"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases your critical strike chance with ranged weapons by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%`,
      },
      "Aimed Shot": {
        name: "Aimed Shot",
        pos: "c1",
        icon: icons["inv_spear_07"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`An aimed shot that increases ranged damage by 70`,
      },
      "Snapshot": {
        name: "Snapshot",
        pos: "e1",
        icon: icons["Snapshot"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Lethal Shots",
        arrows: [{ dir: "down", from: "c1", to: "e1" }],
        description: talentText`Reduces the shot time of your Aimed Shot and Multi Shot by ${[
          0.2,
          0.4,
          0.6,
          0.8,
          1,
        ]} sec.`,
      },
      "Improved Arcane Shot": {
        name: "Improved Arcane Shot",
        pos: "a2",
        icon: icons["ability_impalingbolt"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Increases the critical strike chance of your Arcane Shot by ${[
          15,
          30,
          45,
        ]}%.`,
      },
      "Hawk Eye": {
        name: "Hawk Eye",
        pos: "c4",
        icon: icons["ability_townwatch"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases the range of your ranged weapons by ${[
          3,
          6,
        ]} yards.`,
      },
      "Improved Stings": {
        name: "Improved Stings",
        pos: "c2",
        icon: icons["ability_hunter_quickshot"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases the damage done by your Serpent Sting and Wyvern Sting by ${[
          10,
          20,
          30,
        ]}% and the mana drained by your Viper Sting by ${[
          10,
          20,
          30,
        ]}%. 
        In addition, reduces the Stamina and Intellect of targets affected by your Scorpid Sting by 10% of the amount of Strength reduced.`,
      },
      "Mortal Shots": {
        name: "Mortal Shots",
        pos: "c3",
        icon: icons["ability_piercedamage"],
        maxRank: 5,
        reqPoints: 10,
        prereq: "Lethal Shots",
        arrows: [{ dir: "down", from: "b3", to: "c3" }],
        description: talentText`Increases your ranged weapon critical strike damage bonus by ${[
          6,
          12,
          18,
          24,
          30,
        ]}%.`,
      },
      "Scatter Shot": {
        name: "Scatter Shot",
        pos: "e3",
        icon: icons["ability_golemstormbolt"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`A short range shot that deals 50% wepon damage and disorients the target for 4 sec. Any damage caused will remove the effect. Turns off your attack when used.`,
      },
      "Bullseye": {
        name: "Bullseye",
        pos: "e4",
        icon: icons["Bullseye"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`When activated, increases the critical strike chance of your next Aimed Shot, Multi-Shot or Arcane Shot by 100%.`,
      },
      "Reconnaissance": {
        name: "Reconnaissance",
        pos: "f1",
        icon: icons["Reconnaissance"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases your damage by ${[
          5,
          10,
          15,
          20,
          25,
        ]}% if you are standing still. Usually reconnaissance takes 10 sec.`,
      },

      Barrage: {
        name: "Barrage",
        pos: "e2",
        icon: icons["ability_upgrademoonglaive"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases the damage done by your Multi-Shot and Volley spells by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      "Improved Scorpid Sting": {
        name: "Improved Scorpid Sting",
        pos: "e3",
        icon: icons["ability_hunter_criticalshot"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Reduces the Stamina of targets affected by your Scorpid Sting by ${[
          10,
          20,
          30,
        ]}% of the amount of Strength reduced.`,
      },
      "Crossbow Specialization": {
        name: "Crossbow Specialization",
        pos: "d2",
        icon: icons["crossbow"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Increases your chance to get a critical strike with Crossbows by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Bow Specialization": {
        name: "Bow Specialization",
        pos: "d3",
        icon: icons["bow"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Gives you a ${[
          1,
          2,
          3,
          4,
          5,
        ]}% to launch an extra arrow to the same target after dealing damage with a bow.`,
      },
      "Gun Specialization": {
        name: "Gun Specialization",
        pos: "d4",
        icon: icons["gun"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Gives you a ${[
          2,
          4,
          6,
          8,
          10,
        ]}% to deal additional 3 per level Fire damage and to stun the target for 1 sec when dealing damage with your Gun.`,
      },
      "Ranged Weapon Specialization": {
        name: "Ranged Weapon Specialization",
        pos: "f3",
        icon: icons["inv_weapon_rifle_06"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases the damage your deal with ranged weapons by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Trueshot Aura": {
        name: "Trueshot Aura",
        pos: "g2",
        icon: icons["ability_trueshot"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Barrage",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`Increase the ranged attack power of party members within 45 yards by 100 and melee attack power by 50. Lasts 30 min.`,
      },
    },
  },
  Survival: {
    name: "Survival",
    background: backgrounds["survival"],
    icon: icons["ability_hunter_swiftstrike"],
    talents: {
       Brutality: {
        name: "Brutality",
        pos: "a3",
        icon: icons["brutality"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases your and your pets chance to get a critical strike in melee by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%. Also increases the critical strike chance of Raptor Strike and Mongoose Bite by an additional ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Improved Tracking": {
        name: "Improved Tracking",
        pos: "b2",
        icon: icons["improved_tracking"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`While tracking Beasts, Demons, Dragonkin, Elementals, Giants, Humanoids and Undead, all damage done and critical damage caused to those types by the Hunter is increased by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%. Also increases the effectiveness of Track Hidden.`,
      },
      Deflection: {
        name: "Deflection",
        pos: "a1",
        icon: icons["ability_parry"],
        maxRank: 4,
        reqPoints: 0,
        description: talentText`Increases your Parry chance by ${[
          2,
          4,
          6,
          8,
        ]}%.`,
      },
      "Savage Strikes": {
        name: "Savage Strikes",
        pos: "b1",
        icon: icons["ability_racial_bloodrage"],
        maxRank: 2,
        reqPoints: 5,
        prereq: "Brutality",
        arrows: [{ dir: "down", from: "a1", to: "b1" }],
        description: talentText`Increases the critical strike chance of Raptor Strike and Mongoose Bite by ${[
          5,
          10,
        ]}%.`,
      },
      "Improved Wing Clip": {
        name: "Improved Wing Clip",
        pos: "b3",
        icon: icons["ability_rogue_trip"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Gives your Wing Clip ability a ${[
          5,
          10,
          15,
        ]}% chance to immobilize the target for 5 sec.`,
      },
      "Clever Traps": {
        name: "Clever Traps",
        pos: "b1",
        icon: icons["spell_nature_timestop"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases the duration of Freezing and Frost trap effects by ${[
          15,
          30,
        ]}% and the damage of Immolation and Explosive trap by ${[15, 30]}%.`,
      },
      Survivalist: {
        name: "Survivalist",
        pos: "c3",
        icon: icons["spell_shadow_twilight"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases total health by ${[2, 4, 6, 8, 10]}%. Increases total health by $s1%. In addition, gives your stings an additional 15% chance to resist dispel effects and cures 1 Poison and 1 Disease every 60 sec.`,
      },
      Deterrence: {
        name: "Deterrence",
        pos: "a2",
        icon: icons["ability_whirlwind"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Deterrence",
        arrows: [{ dir: "right", from: "a1", to: "a2" }],
        description: talentText`When activated, gives increase your Dodge and Parry Chance by 25% and reflects the next spell cast on you. Lasts 10 sec.`,
      },
      "Trapper": {
        name: "Trapper",
        pos: "d1",
        icon: icons["ability_ensnare"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Gives your traps a ${[
          10,
          20,
        ]}% chance to entrap the target, preventing them from moving for 5 sec. In addition, decreases the chance enemies will resist Feign Death and trap effects by ${[
          5,
          10,
        ]}%.`,
      },
      "Thrill of the Hunt": {
        name: "Thrill of the Hunt",
        pos: "d4",
        icon: icons["thrill"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Your melee and ranged attacks have a ${[
          10,
          20,
          30,
        ]}% chance to restore 90 Mana.`,
      },
      "Deep Freeze": {
        name: "Deep Freeze",
        pos: "e1",
        icon: icons["deep_freeze"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`While affected by your Freezing Trap, the target receives an additional  ${[
          5,
          10,
          15,
        ]}% damage from all sources and increases the speed reduction of your Frost Trap by ${[
          10,
          20,
          30,
        ]}%.`,
      },
      "Killer Instinct": {
        name: "Killer Instinct",
        pos: "d3",
        icon: icons["spell_holy_blessingofstamina"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Increases your critical strike chance with all attacks by ${[
          1,
          2,
          3,
        ]}% and increases threat generated by pet by 25%.`,
      },
      "Dual Wield Specialization": {
        name: "Dual Wield Specialization",
        pos: "c1",
        icon: icons["dual_wield_spec"],
        maxRank: 4,
        reqPoints: 10,
        prereq: "Melee Specialization",
        arrows: [{ dir: "left", from: "c2", to: "c1" }],
        description: talentText`Increases the damage done by your offhand weapon by ${[
          20,
          40,
          60,
          80
        ]}%.`,
      },
      "Melee Specialization": {
        name: "Melee Specialization",
        pos: "c2",
        icon: icons["melee_spec"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Increases your melee attack speed by 30% but reduces your ranged attack speed by 30% and increases the shot time of your Aimed Shot and Multi-Shot by 1.5 sec.`,
      },
      "Two Handed Specialization": {
        name: "Two Handed Specialization",
        pos: "c3",
        icon: icons["2h_spec"],
        maxRank: 4,
        reqPoints: 20,
        prereq: "Melee Specialization",
        arrows: [{ dir: "right", from: "c2", to: "c3" }],
        description: talentText`Increases the damage done you deal with two-handed melee weapons by ${[
          4,
          8,
          12,
          16
        ]}%.`,
      },
      "Improved Raptor Strike": {
        name: "Improved Raptor Strike",
        pos: "b4",
        icon: icons["improv_raptor_strike"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Brutality",
        arrows: [{ dir: "right-down", from: "a3", to: "a4" },
                 { dir: "right-down-down", from: "a4", to: "b4" },
        ],
        description: talentText`Reduces the cooldown of your Raptor Strike by ${[
          1,
          2,
          3,
          4,
          5
        ]} sec.`,
      },
      "Find Weakness": {
        name: "Find Weakness",
        pos: "f2",
        icon: icons["find_weakness"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Your ranged critical strikes have a ${[
          20,
          40,
          60,
          80,
          100,
        ]}% chance to reveal a flaw in your target's defenses, increasing your melee and ranged damage by 5% for 20 sec. Stacks up to 3 times.`,
      },
      "Lightening Reflexes": {
        name: "Lightening Reflexes",
        pos: "f3",
        icon: icons["spell_nature_invisibilty"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases your Agility by ${[
          4,
          8,
          12,
          16,
          20,
        ]}%`,
      },
      "Wyvern Sting": {
        name: "Wyvern Sting",
        pos: "e3",
        icon: icons["inv_spear_02"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Killer Instinct",
        arrows: [
          { dir: "down", from: "d3", to: "e3" },
        ],
        description: talentText`A stinging shot that puts the target to sleep for 15 sec. Any damage will cancel the effect. When the target wakes up, the Sting causes 300 Nature damage over 12 sec. Only usable out of combat. Only one Sting per Hunter can be active on the target at a time.`,
      },
      "Whirling Axe": {
        name: "Whirling Axe",
        pos: "g2",
        icon: icons["whirling_axe"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`Hurls an axe at a target, causing damage equal to 10% of your melee attack power, stunning the target for 3 sec and slowing target's movement speed by 50% for 8 sec. This attack always crits.`,
      },
      "Savage Blow": {
        name: "Savage Blow",
        pos: "e2",
        icon: icons["savage_blow"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Melee Specialization",
        arrows: [{ dir: "down", from: "c2", to: "e2" }],
        description: talentText`Lethal strike that inflicts 120% weapon damage and applies an effects based on aspects you took on.

Aspect of the Beast: 
Wounds the target, reducing the effectiveness of any healing by 50%,
preventing from fleeing and limiting target's movement speed. Lasts 8 sec.

Aspect of the Cheetah: 
Makes you immune to movement impairing effects for 5 sec.

Aspect of the Hawk: 
Increases the range of Savage Blow by 5 yd.

Aspect of the Monkey: 
Allows to use Mongoose Bite.

Aspect of the Pack: 
Reduces the cost of all spells and abilities
of all nearby party members by 10% for 20 sec.

Aspect of the Wild: 
Regenerates 5% of your total Health over 25 sec.
Stacks up to 5 times.`,
      },

    },
  },
};
