import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/mage"),
);
const icons = requireAll(require.context("../../assets/icons/mage"));

export const data: TalentData = {
  Arcane: {
    name: "Arcane",
    background: backgrounds["arcane"],
    icon: icons["spell_holy_magicalsentry"],
    talents: {
      "Arcane Subtlety": {
        name: "Arcane Subtlety",
        pos: "a1",
        icon: icons["spell_holy_dispelmagic"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`Reduces your target's resistance to all your spells by ${[
          5,
          10,
        ]} and reduces the threat caused by your Arcane spells by ${[
          20,
          40,
        ]}%.`,
      },
      "Arcane Focus": {
        name: "Arcane Focus",
        pos: "a2",
        icon: icons["spell_holy_devotion"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Reduces the chance that the opponent can resist your Arcane spells by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Improved Arcane Missiles": {
        name: "Improved Arcane Missiles",
        pos: "a3",
        icon: icons["spell_nature_starfall"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Gives you a ${[
          20,
          40,
          60,
          80,
          100,
        ]}% chance to avoid interruption caused by damage while channeling Arcane Missiles.`,
      },
      "Wand Specialization": {
        name: "Wand Specialization",
        pos: "b1",
        icon: icons["inv_wand_01"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases your damage with Wands by ${[
          13,
          25,
        ]}%.`,
      },
      "Magic Absorption": {
        name: "Magic Absorption",
        pos: "b2",
        icon: icons["spell_nature_astralrecalgroup"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases all resistances by ${[
          2,
          4,
          6,
          8,
          10,
        ]} and causes all spells you fully resist to restore ${[
          1,
          2,
          3,
          4,
          5,
        ]}% of your total Mana. 1 sec. cooldown.`,
      },
      "Arcane Concentration": {
        name: "Arcane Concentration",
        pos: "b3",
        icon: icons["spell_shadow_manaburn"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Gives you a ${[
          2,
          4,
          6,
          8,
          10,
        ]}% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 100%.`,
      },
      "Magic Attunement": {
        name: "Magic Attunement",
        pos: "c1",
        icon: icons["spell_nature_abolishmagic"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases the effect of your Amplify Magic and Dampen Magic spells by ${[
          25,
          50,
        ]}%.`,
      },
      "Improved Arcane Explosion": {
        name: "Improved Arcane Explosion",
        pos: "c2",
        icon: icons["spell_nature_wispsplode"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases the critical strike chance of your Arcane Explosion spell by an additional ${[
          2,
          4,
          6,
        ]}%.`,
      },
      "Arcane Resilience": {
        name: "Arcane Resilience",
        pos: "c3",
        icon: icons["spell_arcane_arcaneresilience"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Increases your armor by an amount equal to 50% of your Intellect.`,
      },
      "Improved Mana Shield": {
        name: "Improved Mana Shield",
        pos: "d1",
        icon: icons["spell_shadow_detectlesserinvisibility"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Decreases the mana lost per point of damage taken when Mana Sheild is active by ${[
          10,
          20,
        ]}%.`,
      },
      "Improved Counterspell": {
        name: "Improved Counterspell",
        pos: "d2",
        icon: icons["spell_frost_iceshock"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Gives your Counterspell a ${[
          50,
          100,
        ]}% chance to silence the target for 4 sec.`,
      },
      "Arcane Meditation": {
        name: "Arcane Meditation",
        pos: "d4",
        icon: icons["spell_shadow_siphonmana"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Allows ${[
          5,
          10,
          15,
        ]}% of your Mana regeneration to continue while casting.`,
      },
      "Presence of Mind": {
        name: "Presence of Mind",
        pos: "e2",
        icon: icons["spell_nature_enchantarmor"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`When activated, your next Mage spell with a casting time less than 10 sec becomes an instant cast spell.`,
      },
      "Arcane Mind": {
        name: "Arcane Mind",
        pos: "e3",
        icon: icons["spell_shadow_charm"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Arcane Resilience",
        arrows: [{ dir: "down", from: "c3", to: "e3" }],
        description: talentText`Increases your maximum Mana by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Arcane Instability": {
        name: "Arcane Instability",
        pos: "f2",
        icon: icons["spell_shadow_teleport"],
        maxRank: 3,
        reqPoints: 25,
        prereq: "Presence of Mind",
        arrows: [{ dir: "down", from: "e2", to: "f2" }],
        description: talentText`Increases your spell damage critical strike chance by ${[
          1,
          2,
          3,
        ]}%.`,
      },
      "Arcane Power": {
        name: "Arcane Power",
        pos: "g2",
        icon: icons["spell_nature_lightning"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`When activated, your spells deal 30% more damage while costing 30% more mana to cast. This effect lasts 15 sec.`,
      },
    },
  },
  Fire: {
    name: "Fire",
    background: backgrounds["fire"],
    icon: icons["spell_fire_firebolt02"],
    talents: {
      "Improved Fireball": {
        name: "Improved Fireball",
        pos: "a2",
        icon: icons["spell_fire_firebolt02"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Reduces the casting time of your Fireball spell by ${[
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
        ]} sec.`,
      },
      Impact: {
        name: "Impact",
        pos: "a3",
        icon: icons["spell_fire_meteorstorm"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Gives your Fire spells a ${[
          2,
          4,
          6,
          8,
          10,
        ]}% chance to stun the target for 2 sec.`,
      },
      Ignite: {
        name: "Ignite",
        pos: "b1",
        icon: icons["spell_fire_incinerate"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Your critical strikes from Fire damage spells cause the target to burn for an additional ${[
          8,
          16,
          24,
          32,
          40,
        ]}% of your spell's damage over 4 sec.`,
      },
      "Flame Throwing": {
        name: "Flame Throwing",
        pos: "b2",
        icon: icons["spell_fire_flare"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases the range of your Fire spells by ${[
          3,
          6,
        ]} yards.`,
      },
      "Improved Fire Blast": {
        name: "Improved Fire Blast",
        pos: "b3",
        icon: icons["spell_fire_fireball"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Reduces the cooldown of your Fire Blast spell by ${[
          0.5,
          1,
          1.5,
        ]} sec.`,
      },
      Incinerate: {
        name: "Incinerate",
        pos: "c1",
        icon: icons["spell_fire_flameshock"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases the critical strike chance of your Fire Blast and Scorch spells by ${[
          2,
          4,
        ]}%.`,
      },
      "Improved Flamestrike": {
        name: "Improved Flamestrike",
        pos: "c2",
        icon: icons["spell_fire_selfdestruct"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases the critical strike chance of your Flamestrike spell by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      Pyroblast: {
        name: "Pyroblast",
        pos: "c3",
        icon: icons["spell_fire_fireball02"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText``,
      },
    },
  },
};
