import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/paladin"),
);
const icons = requireAll(require.context("../../assets/icons/paladin"));

export const data: TalentData = {
  Holy: {
    name: "Holy",
    background: backgrounds["holy"],
    icon: icons["spell_holy_holybolt"],
    talents: {
      "Divine Strength": {
        name: "Divine Strength",
        pos: "a2",
        icon: icons["spell_holy_auraoflight"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases your Strength by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Divine Intellect": {
        name: "Divine Intellect",
        pos: "a3",
        icon: icons["spell_nature_sleep"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases your total Intellect by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Spiritual Focus": {
        name: "Spiritual Focus",
        pos: "b2",
        icon: icons["spell_arcane_blink"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Gives your damage and healing spells a ${[
          20,
          40,
          60,
        ]}% chance to not lose casting time when you take damage.`,
      },
      "Aura Mastery": {
        name: "Aura Mastery",
        pos: "b1",
        icon: icons["aura_mastery"],
        maxRank:2,
        reqPoints: 5,
        description: talentText`Increases the radius of a Paladin's auras by ${[
          5,
          10,
        ]} yards.`,
      },

      "Improved Seal of Righteousness": {
        name: "Improved Seal of Righteousness",
        pos: "a1",
        icon: icons["ability_thunderbolt"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases the damage done by your Seal of Righteousness and Judgement of Righteousness by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Healing Light": {
        name: "Healing Light",
        pos: "f2",
        icon: icons["spell_holy_holybolt"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases your healing done by ${[
          3,
          6,
          9,
          12,
          15,
        ]}% but reduces all damage done by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      Consecration: {
        name: "Consecration",
        pos: "c2",
        icon: icons["spell_holy_innerfire"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Consecrates the land beneath the Paladin, doing 64 Holy damage over 8 sec to enemies who enter the area.`,
      },
      "Improved Lay on Hands": {
        name: "Improved Lay on Hands",
        pos: "d4",
        icon: icons["spell_holy_layonhands"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Gives the target of your Lay on Hands spell a ${[
          15,
          30,
        ]}% bonus to their armor value from items for 2 min. In addition, the cooldown of your Lay on Hands spell is reduced by ${[
          15,
          30,
        ]} min.`,
      },
      "Unyielding Faith": {
        name: "Unyielding Faith",
        pos: "b4",
        icon: icons["spell_holy_unyieldingfaith"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases your chance to resist Fear and Disorient effects by an additional ${[
          15,
          30,
        ]}%.`,
      },
      "The Long Arm of Justice": {
        name: "The Long Arm of Justice",
        pos: "c4",
        icon: icons["long_arm_of_justice"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases the range of your Judgements, Exorcism and Hammer of Wrath spells by ${[
          5,
          10,
          15,
        ]} yards, the radius of your Holy Wrath by ${[
          3,
          6,
          9,
        ]} yards and reduces the cast time of your Holy Wrath and Hammer of Wrath spells by ${[
          0.5,
          1,
          1.5,
        ]} sec.`,
      },
      "The Shield of Faith": {
        name: "The Shield of Faith",
        pos: "c1",
        icon: icons["shield_of_faith"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Reduces all spell damage taken by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      Illumination: {
        name: "Illumination",
        pos: "d3",
        icon: icons["spell_holy_greaterheal"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Holy Power",
        arrows: [{ dir: "down", from: "b3", to: "d3" }],
        description: talentText`After getting a critical effect from your Flash of Light, Holy Light, or Holy Shock, Exorcism, Holy Wrath or Hammer of Wrath spells, gives you a ${[
          20,
          40,
          60,
          80,
          100,
        ]}% chance to gain Mana equal to the base cost of the spell.`,
      },
      "Divine Wisdom": {
        name: "Divine Wisdom",
        pos: "d1",
        icon: icons["spell_holy_sealofwisdom"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Increases the effect of your Blessings of Wisdom and Light, Seals (and their Judgements) of Wisdom and Light by ${[
          10,
          20,
          30,
        ]}%. In addition, reduces Mana cost of Blessings of Wisdom and Light by ${[
          50,
          100,
        ]}%.`,
      },
      "Improved Purifying": {
        name: "Improved Purifying",
        pos: "d2",
        icon: icons["improved_purifying"],
        maxRank: 3,
        reqPoints: 15,
        prereq: "Consecration",
        arrows: [{ dir: "down", from: "c2", to: "d2" }],
        description: talentText`Reduces the Mana cost of your Cleanse, Purify, Consecration, Exorcism, Holy Wrath and Hammer of Wrath spells by ${[
          10,
          20,
          30,
        ]}% and increases the critical strike chance of your Exorcism, Holy Wrath and Hammer of Wrath spells by ${[
          10,
          20,
          30,
        ]}%.`,
      },
      "The Light's Mercy": {
        name: "The Light's Mercy",
        pos: "e1",
        icon: icons["lights_mercy"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Reduces the cost of your Holy Light, Flash of Light and Holy Shock spells by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      "Inevitable Justice": {
        name: "Inevitable Justice",
        pos: "e2",
        icon: icons["inevitable_justice"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases the critical strike chance of all Judgements capable of a critical hit by ${[
          15,
          30,
          45,
        ]}% and reduces the chance your Seals and Judgements will be dispelled by ${[
          30,
          60,
          90,
        ]}%.`,
      },
      "Lasting Judgement": {
        name: "Lasting Judgement",
        pos: "e3",
        icon: icons["spell_holy_healingaura"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases the duration of your Judgement of Light and Judgement of Wisdom by ${[
          10,
          20,
          30,
        ]} sec.`,
      },
      "Holy Power": {
        name: "Holy Power",
        pos: "b3",
        icon: icons["spell_holy_power"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases the critical effect chance of your Holy Spells by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Searing Light": {
        name: "Searing Light",
        pos: "f3",
        icon: icons["searing_light"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases your damage done by ${[
          3,
          6,
          9,
          12,
          15,
        ]}% but reduces all healing done by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Blinding Light": {
        name: "Blinding Light",
        pos: "g2",
        icon: icons["blinding_light"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`Flash of inner Light emerges from Paladin, making all spells cost no Mana and blinding nearby enemies. Lasts $d. Targets must be facing you. Any damage caused will remove the effect.`,
      },
      "Holy Shock": {
        name: "Holy Shock",
        pos: "e3",
        icon: icons["spell_holy_searinglight"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Illumination",
        arrows: [{ dir: "down", from: "d3", to: "e3" }],
        description: talentText`Blasts the target with Holy energy, causing 204 to 220 Holy damage to an enemy, or 204 to 220 healing to an ally.`,
      },
    },
  },
  Protection: {
    name: "Protection",
    background: backgrounds["protection"],
    icon: icons["spell_holy_devotionaura"],
    talents: {
      "Improved Defensive Auras": {
        name: "Improved Defensive Auras",
        pos: "d1",
        icon: icons["spell_holy_devotionaura"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Increases the armor and resistance bonus of your Devotion and Resistance Auras by ${[
          10,
          20,
          30,
          40,
          50,
        ]}%.`,
      },
      Redoubt: {
        name: "Redoubt",
        pos: "b3",
        icon: icons["ability_defend"],
        maxRank: 5,
        reqPoints: 5,
        prereq: "Shield Specialization",
        arrows: [{ dir: "down", from: "a3", to: "b3" }],
        description: talentText`Gives you a ${[
          4,
          8,
          12,
          16,
          20,
        ]}% chance to increase your chance to block attacks with your shield by 30% for 15 sec or 5 blocks after being hit.  Critical hits have 5 times higher chance to grant the effect.`,
      },
      Precision: {
        name: "Precision",
        pos: "b1",
        icon: icons["ability_rogue_ambush"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your chance to hit with melee weapons by ${[
          1,
          2,
          3,
        ]}% and with spells by ${[
          3,
          6,
          9,
        ]}%.`,
      },
      "Guardian's Favor": {
        name: "Guardian's Favor",
        pos: "b2",
        icon: icons["spell_holy_sealofprotection"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Reduces the cooldown of your Blessing of Protection and Blessing of Freedom by ${[
          30,
          60,
        ]}%, increases the effect of your Blessing of Salvation, Blessing of Sacrifice and Blessing of Sanctuary by ${[
          10,
          20,
        ]} sec and reduces mana cost of listed spells by ${[
          50,
          100,
        ]}%.`,
      },
      Toughness: {
        name: "Toughness",
        pos: "a2",
        icon: icons["spell_holy_devotion"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases your armor value from items by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Blessing of Kings": {
        name: "Blessing of Kings",
        pos: "c1",
        icon: icons["spell_magic_magearmor"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Places a Blessing on a friendly target, increasing total stats by 10% for 5 min. Players may only have one Blessing on them per Paladin at any one time.`,
      },
      "Improved Righteous Fury": {
        name: "Improved Righteous Fury",
        pos: "e1",
        icon: icons["spell_holy_sealoffury"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases the amount of threat generated by your Righteous Fury spell by ${[
          16,
          33,
          50,
        ]}%.`,
      },
      "Vindication": {
        name: "Vindication",
        pos: "c4",
        icon: icons["vindication"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Gives the Paladin's damaging melee attacks a chance to reduce the target's stats by ${[
          15,
          30,
          45,
        ]}% for 10 sec.`,
      },

      "Shield Specialization": {
        name: "Shield Specialization",
        pos: "a3",
        icon: icons["inv_shield_06"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases the amount of damage absorbed by your sheild by ${[
          10,
          20,
          30,
          40,
          50,
        ]}%.`,
      },
      "Improved Hammer of Justice": {
        name: "Improved Hammer of Justice",
        pos: "b4",
        icon: icons["spell_holy_sealofmight"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases the duration of your Hammer of Justice spell by ${[
          0.5,
          1,
          1.5,
        ]} and reduces its cooldown by ${[
          5,
          10,
          15,
        ]} sec.`,
      },
      "Improved Concentration Aura": {
        name: "Improved Concentration Aura",
        pos: "d3",
        icon: icons["spell_holy_mindsooth"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Increases the effect of your Concentration Aura by an additional ${[
          5,
          10,
          15,
        ]}% and gives all group members affected by the aura an additional ${[
          5,
          10,
          15,
        ]}% chance to resist Silence and Interrupt effects.`,
      },
      "Second Wind": {
        name: "Second Wind",
        pos: "d4",
        icon: icons["second_wind"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Gives you a ${[
          5,
          10,
          15,
          20,
          25,
        ]}% chance to generate 1% of your total Mana after being hit.`,
      },

      "Blessing of Sanctuary": {
        name: "Blessing of Sanctuary",
        pos: "c2",
        icon: icons["spell_nature_lightningshield"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Places a Blessing on the friendly target, reducing damage dealt from all sources by up to 10 for 5 min. In addition, when the target blocks a melee attack the attacker will take 10 Holy damage. Players may only have one Blessing on them per Paladin at any one time.`,
      },
      Reckoning: {
        name: "Reckoning",
        pos: "f3",
        icon: icons["spell_holy_blessingofstrength"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Gives you a ${[
          4,
          8,
          12,
          16,
          20,
        ]}% chance to gain an extra attack after being hit by an attack or spell. Critical Strikes have 5 times higher chance to grant an extra attack.`,
      },
      "One-Handed Weapon Specialization": {
        name: "One-Handed Weapon Specialization",
        pos: "c3",
        icon: icons["inv_sword_20"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases the damage you deal with one-handed melee weapons by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Anticipation": {
        name: "Anticipation",
        pos: "e3",
        icon: icons["anticipation"],
        maxRank: 5,
        reqPoints: 20,
        description: talentText`Reduces chance you are hit by spells and ranged attacks by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Morale": {
        name: "Morale",
        pos: "f1",
        icon: icons["morale"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases your chance to resist Fear and Charm effects by ${[
          10,
          20,
          30,
          40,
          50,
        ]}%. In addition, your melee attacks have a ${[
          2,
          4,
          6,
          8,
          10,
        ]}% chance to restore 125 Mana.`,
      },
      "Holy Shield": {
        name: "Holy Shield",
        pos: "e2",
        icon: icons["classic_spell_holy_blessingofprotection"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Blessing of Sanctuary",
        arrows: [{ dir: "down", from: "c2", to: "e2" }],
        description: talentText`Increases chance to block by 30% for 10 sec, and deals 45 Holy damage for each attack blocked while active. Damage caused by Holy Shield causes 20% additional threat. Each block expends a charge. 4 charges.`,
      },
      "Improved Holy Shield": {
        name: "Improved Holy Shield",
        pos: "f2",
        icon: icons["classic_spell_holy_blessingofprotection"],
        maxRank: 2,
        reqPoints: 25,
        prereq: "Holy Shield",
        arrows: [{ dir: "down", from: "e2", to: "f2" }],
        description: talentText`Allows your Holy Shield spell to block an additional ${[
          2,
          4,
        ]} attacks and increases the duration by ${[
          5,
          10,
        ]} second.`,
      },
      "Seal of Fury": {
        name: "Seal of Fury",
        pos: "g2",
        icon: icons["seal_of_fury"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`Fills the Paladin with divine fury for 30 sec, causing all melee attacks deals additional Holy damage equal to 25% of normal weapon damage to all targets infront Paladin. Only one Seal can be active on the Paladin at any one time. \n\nUnleashing this Seal's energy will judge an enemy for 4 sec, forcing the target to attack you, but has no effect if the target is already attacking you.`,
      },
    },
  },
  Retribution: {
    name: "Retribution",
    background: backgrounds["retribution"],
    icon: icons["spell_holy_auraoflight"],
    talents: {
      "Improved Blessing of Might": {
        name: "Improved Blessing of Might",
        pos: "a2",
        icon: icons["spell_holy_fistofjustice"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases the melee attack power bonus of your Blessing of Might by ${[
          4,
          8,
          12,
          16,
          20,
        ]}%.`,
      },
      Benediction: {
        name: "Benediction",
        pos: "a3",
        icon: icons["spell_frost_windwalkon"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Reduces the Mana cost of your Judgement and Seal spells by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Improved Judgement": {
        name: "Improved Judgement",
        pos: "b1",
        icon: icons["spell_holy_righteousfury"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Decreases the cooldown of your Judgement spell by ${[
          1,
          2,
        ]} sec.`,
      },
      "Improved Seal of the Crusader": {
        name: "Improved Seal of the Crusader",
        pos: "b2",
        icon: icons["spell_holy_holysmite"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases the melee attack power bonus of your Seal of the Crusader and the Holy damage increase of your Judgement of the Crusader by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      Deflection: {
        name: "Deflection",
        pos: "b3",
        icon: icons["ability_parry"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases your Parry chance by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      Vindication: {
        name: "Vindication",
        pos: "c1",
        icon: icons["spell_holy_vindication"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Gives the Paladin's damaging melee attacks a chance to reduce the target's Strength and Agility by ${[
          5,
          10,
          15,
        ]}% for 10 sec.`,
      },
      Conviction: {
        name: "Conviction",
        pos: "c2",
        icon: icons["spell_holy_retributionaura"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases your chance to get a critical strike with melee weapons by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Seal of Command": {
        name: "Seal of Command",
        pos: "c3",
        icon: icons["ability_warrior_innerrage"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Gives the Paladin a chance to deal Holy damage equal to 70% of normal weapon damage. Only one Seal can be active on the Paladin at any one time. Lasts 30 sec.\n\nUnleashing this Seal's energy will judge an enemy, instantly causing 90 to 95 Holy damage, 137 to 146 if the target is stunned or incapacitated.`,
      },
      "Pursuit of Justice": {
        name: "Pursuit of Justice",
        pos: "c4",
        icon: icons["spell_holy_persuitofjustice"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases movement and mounted movement speed by ${[
          4,
          8,
        ]}%. This does not stack with other movement speed increasing effects.`,
      },
      "Eye for an Eye": {
        name: "Eye for an Eye",
        pos: "d1",
        icon: icons["spell_holy_eyeforaneye"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`All spell criticals against you cause ${[
          15,
          30,
        ]}% of the damage taken to the caster as well. The damage caused by Eye for an Eye will not exceed 50% of the Paladin's total health.`,
      },
      "Improved Retribution Aura": {
        name: "Improved Retribution Aura",
        pos: "d3",
        icon: icons["spell_holy_auraoflight"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Increases the damage done by your Retribution Aura by ${[
          25,
          50,
        ]}%.`,
      },
      "Two-Handed Weapon Specialization": {
        name: "Two-Handed Weapon Specialization",
        pos: "e1",
        icon: icons["inv_hammer_04"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases the damage you deal with two-handed melee weapons by ${[
          2,
          4,
          6,
        ]}%.`,
      },
      "Sanctity Aura": {
        name: "Sanctity Aura",
        pos: "e3",
        icon: icons["spell_holy_mindvision"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Increases Holy damage done by party members within 30 yards by 10%. Players may only have one Aura on them per Paladin at any one time.`,
      },
      Vengence: {
        name: "Vengence",
        pos: "f2",
        icon: icons["ability_racial_avatar"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Conviction",
        arrows: [{ dir: "down", from: "c2", to: "f2" }],
        description: talentText`Gives you a ${[
          3,
          6,
          9,
          12,
          15,
        ]}% bonus to Physical and Holy damage you deal for 8 sec after dealing a critical strike from a weapon swing, spell, or ability.`,
      },
      Repentence: {
        name: "Repentence",
        pos: "g2",
        icon: icons["spell_holy_prayerofhealing"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`Puts the enemy target in a state of meditation, incapacitating them for up to 6 sec. Any damage caused will awaken the target. Only works against Humanoids.`,
      },
    },
  },
};
