import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/rogue"),
);
const icons = requireAll(require.context("../../assets/icons/rogue"));

export const data: TalentData = {
  Assassination: {
    name: "Assassination",
    background: backgrounds["assassination"],
    icon: icons["ability_rogue_eviscerate"],
    talents: {
      "Improved Eviscerate": {
        name: "Improved Eviscerate",
        pos: "a1",
        icon: icons["ability_rogue_eviscerate"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Increases the damage done by your Eviscerate ability by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      "Remorseless Attacks": {
        name: "Remorseless Attacks",
        pos: "a2",
        icon: icons["ability_rogue_feigndeath"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`After killing a target that yields experience or honor, gives you a ${[
          20,
          40,
        ]}% increased critical strike chance on your next Sinister Strike, Backstab, Ambush, or Ghostly Strike. Lasts 20 sec.`,
      },
      "Malice": {
        name: "Malice",
        pos: "a4",
        icon: icons["ability_racial_bloodrage"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases your critical strike chance by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Ruthlessness": {
        name: "Ruthlessness",
        pos: "b1",
        icon: icons["ability_druid_disembowel"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Gives your finishing moves a ${[
          20,
          40,
          60,
        ]}% chance to add a combo point to your target.`,
      },
      "Improved Expose Armor": {
        name: "Improved Expose Armor",
        pos: "b2",
        icon: icons["ability_warrior_riposte"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increase the amount of armor reduced by your Expose Armor by ${[
          25,
          50,
        ]}% and reduces the energy cost of your Expose Armor by ${[
          5,
          10,
        ]}`,
      },
      "Improved Backstab": {
        name: "Improved Backstab",
        pos: "b3",
        icon: icons["ability_backstab"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases the critical chance of your backstab ability by ${[
          10,
          20,
          30,
        ]}%.`,
      },
      "Relentless Strikes": {
        name: "Relentless Strikes",
        pos: "c1",
        icon: icons["ability_warrior_decisivestrike"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Your finishing moves have a ${[
		  20,
		  40,
		]}% chance per combo point to restore 25 energy.`,
      },
      "Vile Poison Mastery": {
        name: "Vile Poison Mastery",
        pos: "c2",
        icon: icons["ability_rogue_feigndeath"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases the damage dealt by your poisons by ${[
          4,
          8,
          12,
          16,
          20,
        ]}% and gives your poisons an additional ${[
          8,
          16,
          24,
          32,
          40,
        ]}% chance to resist dispel effects. Addtitionally Increases the chance to apply poisons to your target by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      Lethality: {
        name: "Lethality",
        pos: "c4",
        icon: icons["ability_criticalstrike"],
        maxRank: 5,
        reqPoints: 10,
        prereq: "Malice",
        arrows: [{ dir: "down", from: "a4", to: "c4" }],
        description: talentText`Increases the critical strike damage bonus of your Sinister Strike, Gouge, Backstab, Ghostly Strike, and Hemorrhage abilities by ${[
          6,
          12,
          18,
          24,
          30,
        ]}%.`,
      },
      "Poison Paragon": {
        name: "Poison Paragon",
        pos: "d1",
        icon: icons["Ability_creature_poison_05"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Increases the critical strike chance of all attacks made against any target you have poisoned by ${[
          1,
          2,
          3,
        ]}% and reduces the duration of all poison effects applied to you by ${[
          17,
		  34,
		  50,
        ]}% `,
      },
      "Quick Recovery": {
        name: "Quick Recovery",
        pos: "d3",
        icon: icons["ability_warrior_revenge"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`All healing effects on you are increased ${[
          10,
          20,      
        ]}%. In addition, your finishing moves cost ${[
		40,
		80,
		]}% less energy when they fail to hit`,
      },
	  "Improved Kidney Shot": {
        name: "Improved Kidney Shot",
        pos: "d4",
        icon: icons["ability_rogue_kidneyshot"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`While affected by your Kidney Shot ability, the target receives an additional ${[
          3,
          6,
          9,
        ]}% damage from all sources.`,
      },
	  "Fel Poisons": {
		name: "Fel Poisons",
		pos: "e1",
		icon: icons["ability_poisons"],
		maxRank: 1,
		reqPoints: 20,
		description: talentText`Your poisons are infused with Fel magic and can effect Elementals and Mechanical creatures.`
	  },
      "Cold Blood": {
        name: "Cold Blood",
        pos: "e3",
        icon: icons["spell_ice_lament"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`When activated, increases the critical strike chance of your next Sinister Strike, Backstab, Ambush, or Eviscerate by 100%.`,
      },
	  "Thirst for Blood": {
        name: "Thirst for Blood",
        pos: "e4",
        icon: icons["ability_warrior_warcry"],
        maxRank: 5,
        reqPoints: 20,
        description: talentText`Your melee critical strikes have a ${[
          20,
          40,
          60,
          80,
          100,
        ]}% chance to generate ${[
          1,
          2,
          3,
          4,
          5,
        ]}energy.`,
      },
      "Envenom": {
        name: "Envenom",
        pos: "f2",
        icon: icons["ability_rogue_dualweild"],
        maxRank: 1,
        reqPoints: 25,
		prereq: "Vile Poison Mastery",
		arrows: [{ dir: "down", from: "c2", to: "f2" }],
        description: talentText`Finishing move that consumes your Deadly Poison doses on the target and deals instant poison damage. Following the Envenom attack you have an additional 15% chance to apply Deadly Poison and a 75% increased frequency of applying Instant Poison for 1 sec plus an additional 1 sec per combo point. One dose is consumed for each combo point:.`,
      },
      "Seal Fate": {
        name: "Seal Fate",
        pos: "f3",
        icon: icons["spell_shadow_chilltouch"],
        maxRank: 4,
        reqPoints: 25,
        prereq: "Cold Blood",
        arrows: [{ dir: "down", from: "e3", to: "f3" }],
        description: talentText`Your critical strikes from abilities that add combo points have a ${[
          25,
          50,
          75,
          100,
        ]}% chance to add an additional combo point.`,
      },
      "Poison Thrill": {
        name: "Poison Thrill",
        pos: "g2",
        icon: icons["spell_nature_earthbindtotem"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`Increases your maximum Energy by 10. In addition, every time you poison an enemy you gain a 5% increase to your energy regeneration rate for 15 sec, stacks 4 time `,
      },
    },
  },
  Combat: {
    name: "Combat",
    background: backgrounds["combat"],
    icon: icons["ability_backstab"],
    talents: {
      "Improved Gouge": {
        name: "Improved Gouge",
        pos: "a1",
        icon: icons["ability_gouge"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Increases the effect duration of your Gouge ability by ${[
          0.5,
          1,
          1.5,
        ]} sec.`,
      },
      "Improved Sinister Strike": {
        name: "Improved Sinister Strike",
        pos: "a2",
        icon: icons["spell_shadow_ritualofsacrifice"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`Reduces the Energy cost of your Sinister Strike ability by ${[
          3,
          5,
        ]}.`,
      },
      "Precision": {
        name: "Precision",
        pos: "a4",
        icon: icons["ability_marksmanship"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases your chance to hit with melee weapons by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Improved Slice and Dice": {
        name: "Improved Slice and Dice",
        pos: "b1",
        icon: icons["ability_rogue_slicedice"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases the duration of your Slice and Dice ability by ${[
          15,
          30,
          45,
        ]}%.`,
      },
      "Deflection": {
        name: "Deflection",
        pos: "b2",
        icon: icons["ability_parry"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases your Parry chance by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Endurance Runner": {
        name: "Endurance Runner",
        pos: "c1",
        icon: icons["spell_shadow_shadowward"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Reduces the cooldown of your Sprint and Evasion abilities by ${[
          "45 sec",
          "1.5 min",
        ]} and gives your sprint ability a ${[
		  50,
		  100,
		]}% chance to remove all movement impairing effects`,
      },
      "Riposte": {
        name: "Riposte",
        pos: "c2",
        icon: icons["ability_warrior_challange"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Deflection",
        arrows: [{ dir: "down", from: "b2", to: "c2" }],
        description: talentText`A strike that becomes active after parrying an opponent's attack. This attack deals 150% weapon damage and disarms the target for 6 sec.`,
      },
      "Dual Wield Specialization": {
        name: "Dual Wield Specialization",
        pos: "c4",
        icon: icons["ability_dualwield"],
        maxRank: 5,
        reqPoints: 10,
        prereq: "Precision",
        arrows: [{ dir: "down", from: "a4", to: "c4" }],
        description: talentText`Increases damage done by your offhand weapon by ${[
          10,
          20,
          30,
          40,
          50,
        ]}%.`,
      },
      "Improved Kick": {
        name: "Improved Kick",
        pos: "d1",
        icon: icons["ability_kick"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Gives your Kick ability a ${[
          50,
          100,
        ]}% chance to silence the target for 4 sec.`,
      },
      "Close Quarter Specialization": {
        name: "Close Quarter Specialization",
        pos: "d2",
        icon: icons["inv_weapon_shortblade_05"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Increases your chance to get a critical strike with Daggers and Fist Weapons by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%. In addition, increases your skill with Daggers and Fist Weapons by ${[
		  1,
		  2,
		  3,
		  4,
		  5,
		]}.`,
      },
       Aggression: {
        name: "Aggression",
        pos: "d3",
        icon: icons["ability_racial_avatar"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Increases the damage of your Sinister Strike and Eviscerate abilities by ${[
          2,
          4,
          6,
		  8,
		  10,
        ]}%.`,
      },
      "Mace Specialization": {
        name: "Mace Specialization",
        pos: "e1",
        icon: icons["inv_mace_01"],
        maxRank: 5,
        reqPoints: 20,
        description: talentText`Your attacks with maces ignore ${[
          1,
          2,
          3,
          4,
          5,
        ]}% of your target's armor. In addition increases your skill with maces by ${[
          1,
          2,
          3,
          4,
          5,
        ]}.`,
      },
      "Blade Flurry": {
        name: "Blade Flurry",
        pos: "e2",
        icon: icons["ability_warrior_punishingblow"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Increases your attack speed by 20%. In addition, attacks strike an additional nearby opponent. Lasts 15 sec.`,
      },
      "Sword Specialization": {
        name: "Sword Specialization",
        pos: "e3",
        icon: icons["inv_sword_27"],
        maxRank: 5,
        reqPoints: 20,
        description: talentText`Gives you a ${[
          1,
          2,
          3,
          4,
          5,
        ]}% chance to get an extra attack on the same target after dealing damage with your Sword. In addition increases your skill with swords by ${[
		  1,
		  2,
		  3,
		  4,
		  5,
		]}.`,
      },
      "Cut to the Chase": {
        name: "Cut to the Chase",
        pos: "f2",
        icon: icons["spell_shadow_charm"],
        maxRank: 3,
        reqPoints: 25,
		prereq: "Blade Flurry",
        arrows: [{ dir: "down", from: "e2", to: "f2" }],
        description: talentText`Your eviscerate ability have a ${[
          20,
          40,
          60,
        ]}% chance to refresh your Slice and Dice duration to its 5 combo point maximum.`,
      },
      "Lightning Reflexes": {
        name: "Lightning Reflexes",
        pos: "f3",
        icon: icons["spell_nature_invisibilty"],
        maxRank: 3,
        reqPoints: 25,
        description: talentText`Increases chance to dodge by ${[
          2,
          4,
		  6,
	    ]}%. In addition increases your melee attack speed by ${[
		  4,
		  7,
		  10,
		]}%.`,
      },
      "Adrenaline Rush": {
        name: "Adrenaline Rush",
        pos: "g2",
        icon: icons["spell_shadow_shadowworddominate"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`Increases your Energy regeneration rate by 100% for 15 sec.`,
      },
    },
  },
  Subtlety: {
    name: "Subtlety",
    background: backgrounds["subtlety"],
    icon: icons["ability_stealth"],
    talents: {
      "Master of Deception": {
        name: "Master of Deception",
        pos: "a2",
        icon: icons["spell_shadow_charm"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`Reduces the chance enemies have to detect you while in Stealth mode.${[
          "",
          " More effective than Master of Deception (Rank 1)",
          " More effective than Master of Deception (Rank 2)",
        ]}.`,
      },
      Opportunity: {
        name: "Opportunity",
        pos: "a3",
        icon: icons["ability_warrior_warcry"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases the damage dealt when striking from behind with your Backstab, Garrote, or Ambush abilities by ${[
          4,
          8,
          12,
          16,
          20,
        ]}%.`,
      },
      "Street Smart": {
        name: "Street Smart",
        pos: "a4",
        icon: icons["inv_weapon_shortblade_17"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Increases the range of your pickpocket ability by ${[
          1,
		      2,
          3,
        ]} yards, reduces the cooldown of your Distraction and Disarm Trap abilities by ${[
          25,
          50,
          75,
        ]}% and reduces the cost of your Distract ability by ${[
          33,
          66,
          100,
        ]}%. In addition, increases your reputation gains by ${[
          2,
          4,
          6,
        ]}%.`,
      },
      "Elusive Shadow": {
        name: "Elusive Shadow",
        pos: "b1",
        icon: icons["ability_rogue_feint"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Reduces the chance you are critically hit by melee and ranged attacks by ${[
          2,
          4,
        ]}% and reduces the cooldown of your Vanish and Blind abilities by ${[
          "45 sec",
          "1.5 min",
        ]}%.`,
      },
      "Master of Camouflage": {
        name: "Master of Camouflage",
        pos: "b3",
        icon: icons["spell_magic_lesserinvisibilty"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your speed while stealthed by ${[
          5,
          10,
          15,
        ]}% and reduces the cooldown of your Stealth ability by ${[
          2,
          4,
          5,
        ]} sec.`,
      },
      "Dirty tricks": {
        name: "Dirty Tricks",
        pos: "b4",
        icon: icons["ability_sap"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases the range of your Blind and Sap abilities by ${[
          2,
          5,
        ]} yards and reduces the cost of your Blind and Sap abilities by ${[
          25,
          50,
        ]} %.`,
      },
      Initiative: {
        name: "Initiative",
        pos: "c1",
        icon: icons["spell_shadow_fumble"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Gives you a ${[
          33,
          66,
          100,
        ]}% chance to add an additional combo point to your target when using your Ambush, Garrote, or Cheap Shot ability.`,
      },
      "Ghostly Strike": {
        name: "Ghostly Strike",
        pos: "c2",
        icon: icons["spell_shadow_curse"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`A strike that deals 125% weapon damage and increases your chance to dodge by 15% for 7 sec. Awards 1 combo point.`,
      },
      "Improved Ambush": {
        name: "Improved Ambush",
        pos: "c3",
        icon: icons["ability_rogue_ambush"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases the critical strike chance of your Ambush ability by ${[
          15,
          30,
          45,
        ]}%.`,
      },
      Setup: {
        name: "Setup",
        pos: "d1",
        icon: icons["spell_nature_mirrorimage"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Gives you a ${[
          25,
          50,
          75,
        ]}% chance to add a combo point to your target after dodging their attack or fully resisting one of their spells.`,
      },
      "Serrated Blades": {
        name: "Serrated Blades",
        pos: "d3",
        icon: icons["inv_sword_17"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Causes your attacks to ignore 0 of your target's Armor and increases the damage dealt by your Rupture ability by ${[
          10,
          20,
          30,
        ]}%. The amount of Armor reduced increases with your level.`,
      },
      "Enveloping Shadows": {
        name: "Enveloping Shadows",
        pos: "e1",
        icon: icons["ability_stealth"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your chance to avoid area of effect attacks by ${[
          5,
          10,
		  15,
        ]}%.`,
      },
      Preparation: {
        name: "Preparation",
        pos: "e2",
        icon: icons["spell_shadow_antishadow"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`When activated, this ability immediately finishes the cooldown on your other Rogue abilities.`,
      },
      "Dirty Deeds": {
        name: "Dirty Deeds",
        pos: "e3",
        icon: icons["spell_shadow_summonsuccubus"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Reduces the Energy cost of your Cheap Shot and Garrote abilities by ${[
          10,
          20,
        ]}.`,
      },
      Hemmorhage: {
        name: "Hemmorhage",
        pos: "e4",
        icon: icons["spell_shadow_lifedrain"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Serrated Blades",
        arrows: [
          { dir: "right-down", from: "d3", to: "d4" },
          { dir: "right-down-down", from: "d4", to: "e4" },
        ],
        description: talentText`An instant strike that damages the opponent and causes the target to hemmorhage, increasing any Physical damage dealt to the target by up to 3. Lasts 30 charges or 15 sec. Awards 1 combo point.`,
      },
      "Master of Shadows": {
        name: "Master of Shadows",
        pos: "f1",
        icon: icons["ability_ambush"],
        maxRank: 2,
        reqPoints: 25,
        prereq: "Enveloping Shadows",
        arrows: [{ dir: "down", from: "e1", to: "f1" }],
        description: talentText`Attacks made while stealthed and for 6 sec after breaking stealth cause an extra ${[
          5,
          10,
        ]}% damage. In addition, increases your stealth detection and reduces the chance you are hit by spells and ranged attacks by ${[
          2,
          4,
        ]}%.`,
      },
      Deadliness: {
        name: "Deadliness",
        pos: "f3",
        icon: icons["inv_weapon_crossbow_11"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases your Attack Power by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Shadow Dance": {
        name: "Shadow Dance",
        pos: "g2",
        icon: icons["spell_shadow_possession"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`Enter the Shadow Dance for 6 sec, allowing the use of Sap, Garrote, Ambush, Cheap Shot, Pickpocket and Disarm Trap regardless of being stealthed.`,
      },
    },
  },
};
